src/Entity/Admin/trip.php
<?php

namespace App\Entity\Admin;


use App\Entity\Category;
use App\Entity\User;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Admin\Image;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Admin\tripRepository")
 */
class trip
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $keywords;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;




    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $trip_start;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $trip_end;

    /**
     * @ORM\OneToOne(targetEntity="Image")
     * @ORM\JoinColumn(onDelete="SET NULL")
     *
     */
    private $image;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    private $publisher;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    private $category;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Admin\Image")
     */
    private $images;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Admin\Image", mappedBy="trip")
     */
    private $yes;

    /**
     * @ORM\Column(type="string", length=25, nullable=true)
     */
    private $status;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->yes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }



    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }

    public function setKeywords(?string $keywords): self
    {
        $this->keywords = $keywords;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }


    public function getTripStart(): ?\DateTimeInterface
    {
        return $this->trip_start;
    }

    public function setTripStart(?\DateTimeInterface $trip_start): self
    {
        $this->trip_start = $trip_start;

        return $this;
    }

    public function getTripEnd(): ?\DateTimeInterface
    {
        return $this->trip_end;
    }

    public function setTripEnd(?\DateTimeInterface $trip_end): self
    {
        $this->trip_end = $trip_end;

        return $this;
    }

    public function getImage(): ?Image
    {
        return $this->image;
    }

    public function setImage(?Image $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getPublisher(): ?User
    {
        return $this->publisher;
    }

    public function setPublisher(?User $publisher): self
    {
        $this->publisher = $publisher;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function __toString()
    {
        // TODO: Implement __toString() method.
        return $this->getTitle();
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
        }

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getYes(): Collection
    {
        return $this->yes;
    }

    public function addYe(Image $ye): self
    {
        if (!$this->yes->contains($ye)) {
            $this->yes[] = $ye;
            $ye->setTrip($this);
        }

        return $this;
    }

    public function removeYe(Image $ye): self
    {
        if ($this->yes->contains($ye)) {
            $this->yes->removeElement($ye);
            // set the owning side to null (unless already changed)
            if ($ye->getTrip() === $this) {
                $ye->setTrip(null);
            }
        }

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }
}

src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Entity\Admin\trip;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentRepository")
 */
class Comment
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $commented_by;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Admin\trip")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $on_trip;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $commented_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $subject;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $rating;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $ip;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getCommentedBy(): ?User
    {
        return $this->commented_by;
    }

    public function setCommentedBy(?User $commented_by): self
    {
        $this->commented_by = $commented_by;

        return $this;
    }

    public function getOnTrip(): ?trip
    {
        return $this->on_trip;
    }

    public function setOnTrip(?trip $on_trip): self
    {
        $this->on_trip = $on_trip;

        return $this;
    }

    public function getCommentedAt(): ?\DateTimeInterface
    {
        return $this->commented_at;
    }

    public function setCommentedAt(?\DateTimeInterface $commented_at): self
    {
        $this->commented_at = $commented_at;

        return $this;
    }

    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function setSubject(?string $subject): self
    {
        $this->subject = $subject;

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(?int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(?bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getIp(): ?string
    {
        return $this->ip;
    }

    public function setIp(?string $ip): self
    {
        $this->ip = $ip;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Entity/Saved.php
<?php

namespace App\Entity;

use App\Entity\Admin\trip;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SavedRepository")
 */
class Saved
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Admin\trip")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $trip;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $user;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $added_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTrip(): ?trip
    {
        return $this->trip;
    }

    public function setTrip(?trip $trip): self
    {
        $this->trip = $trip;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getAddedAt(): ?\DateTimeInterface
    {
        return $this->added_at;
    }

    public function setAddedAt(?\DateTimeInterface $added_at): self
    {
        $this->added_at = $added_at;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email')
            ->add('name')
            ->add('surname')
          //  ->add('roles')
          ->add('roles' ,  ChoiceType::class,[
              'choices' => [
                   'Admin' => "ROLE_ADMIN",
                   'User' => "ROLE_USER" ],


          ])
          ->add('password', PasswordType::class, [
              // instead of being set onto the object directly,
              // this is read and encoded in the controller
              'mapped' => false,
              'constraints' => [
                  new NotBlank([
                      'message' => 'Please enter a password',
                  ]),
                  new Length([
                      'min' => 6,
                      'minMessage' => 'Your password should be at least {{ limit }} characters',
                      // max length allowed by Symfony for security reasons
                      'max' => 4096,
                  ]),
              ],
          ])
            ->add('status' ,  ChoiceType::class,[
                'choices' => [
                    'True' => 'True',
                    'False' => 'False'],

            ]);
        ;
        // role file data
        $builder->get('roles')->addModelTransformer(new CallbackTransformer(
            function ($roleArray){
                return count($roleArray)? $roleArray[0]: null;
            },
            function ($roleString) {
                return [$roleString];
            }

        ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/Admin/UserController.php
<?php

namespace App\Controller\Admin;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/admin/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="admin_user_index", methods={"GET"})
     * @param UserRepository $userRepository
     * @return Response
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('admin/admin/user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="admin_user_new", methods={"GET","POST"})
     * @param Request $request
     * @param UserPasswordEncoderInterface $passwordEncoder
     * @return Response
     */
    public function new(Request $request, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            ////////////
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('password')->getData()
                )
            );
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('admin_user_index');
        }

        return $this->render('admin/admin/user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('admin/admin/user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="admin_user_edit", methods={"GET","POST"})
     * @param Request $request
     * @param User $user
     * @param UserPasswordEncoderInterface $passwordEncoder
     * @return Response
     */
    public function edit(Request $request, User $user,UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            ////////////
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('password')->getData()
                )
            );

            return $this->redirectToRoute('admin_user_index');
        }

        return $this->render('admin/admin/user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_user_delete", methods={"DELETE"})
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_user_index');
    }
}

templates/home/User/upload-user-profile.html.twig
{% extends 'admin/admin/image/image-base.html.twig' %}
{% block body %}
    <div style="padding-top: 20px;">
        <div class="container">
            <div class="card-view">
                <div class="card-header" style="">
                    {{ include('admin/admin/image/_form.html.twig') }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/home/User/user-comment-edit.html.twig
{% extends('admin/homeBase.html.twig') %}

{% block body %}
    {% include('home/User/user-upper.html.twig') %}
    {% form_theme form 'bootstrap_4_layout.html.twig' %}
    {% include ('admin/admin/comment/_form.html.twig') %}
    {% include('home/User/user-lower.html.twig') %}
{% endblock %}

templates/home/User/user-comment.html.twig
{% extends('admin/homeBase.html.twig') %}

{% block body %}
    {% include('home/User/user-upper.html.twig') %}
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Subject</th>
                <th>Rating</th>
                <th>Comment</th>
                <th>Commented At</th>
                <th>Status</th>
                <th>Delete</th>
                <th>Edit</th>
            </tr>
            </thead>
            <tbody>
                {% for comment in comments %}
                    <tr>
                        <th>{{ comment.subject }}</th>
                        <th>{{ comment.rating }}</th>
                        <th class="text-truncate">{{ comment.comment }}</th>
                        <th>{{ comment.commentedAt |date("m/d/Y") }}</th>
                        <th>{{ comment.status ? "Visible" : "Hidden" }}</th>
                        <th>{{ include('admin/admin/comment/_delete_form.html.twig') }}</th>
                        <th><a href="{{ path('user-profile-comment-edit', {'id' : comment.id}) }}" class="btn btn-primary" style="text-transform:lowercase;">Edit</a></th>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% include('home/User/user-lower.html.twig') %}
{% endblock %}

templates/home/User/user-index.html.twig
{% extends('admin/homeBase.html.twig') %}

{% block body %}
    {% include('home/User/user-upper.html.twig') %}
        <div class="container">
            <div class="col col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div class="">
                            General Setting
                        </div>
                    </div>
                    <div class="card-body">
                        <h5>Change Username</h5>
                        <form action="?task=username" method="post" class="">
                            <div class="form-group">
                                <label for="">Username</label>
                                <input class="form-control" type="text" name="user[name]" value="{{ app.user.username }}">
                            </div>
                            <input type="submit" value="Change Name" class="btn btn-success">
                        </form>
                        <br>
                        <hr>
                        <h5>Change Password</h5>
                        <form action="?task=password" method="post" class="">
                            <div class="form-group">
                                <label for="">New Password</label>
                                <input class="form-control" type="password" name="user[password]">
                            </div>
                            <div class="form-group">
                                <label for="">ReType New Password</label>
                                <input class="form-control" type="password" name="repassword">
                            </div>
                            <input type="submit" value="Change Password" class="btn btn-success">
                        </form>

                    </div>
                </div>
            </div>
        </div>
    {% include('home/User/user-lower.html.twig') %}
{% endblock %}

templates/home/User/user-joined-trips.html.twig
{% extends('admin/homeBase.html.twig') %}

{% block body %}
    {% include('home/User/user-upper.html.twig') %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Trip Title</th>
            <th>Trip's Price</th>
            <th>Trip's Start Date</th>
            <th>Added At</th>
            <th>Status</th>
            <th>View</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for joined in joineds %}
            <tr>
                <th>{{ joined.trip.title }}</th>
                <th>{{ joined.trip.price }}</th>
                <th>{{ joined.trip.tripStart|date("m/d/Y") }}</th>
                <th>{{ joined.addedAt |date("m/d/Y") }}</th>
                <th>{{ joined.status }}</th>
                <th><a href="{{ path('trip_detail', {'id' : joined.trip.id}) }}" class="btn btn-sm btn-info">View</a></th>
                <th>
                    {% if joined.status == "Pending" %}
                    <form method="post" action="{{ path('delete-joined-list', {'id': joined.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ joined.id) }}">
                        <button class="btn btn-sm btn-danger">Delete</button>
                    </form>
                    {% else %}
                        <button onclick="onWarning()" class="btn btn-sm btn-danger"> Delete</button>
                    {% endif %}
                </th>
            </tr>
        {% else %}
            <h5>You Haven't Join Any Trip Yet.</h5>
        {% endfor %}
        </tbody>
        <script>
            function onWarning() {
                window.alert("Trip Has Been Accepted. Can't delete trip.")
            }
        </script>
    </table>
    {% include('home/User/user-lower.html.twig') %}
{% endblock %}

templates/home/User/user-lower.html.twig
</div>
</div>
</div>
<hr>

templates/home/User/user-my-trip-show.html.twig
{% extends('admin/homeBase.html.twig') %}
{#<title>trip</title>#}

{% block body %}
    {% include('home/User/user-upper.html.twig') %}
    <div class="container-fluid">
        <div class="">
            <h1 class="floatleft">Trip</h1>
            <a class="btn btn-info btn-sm floatright" href="{{ path('admin_trip_index') }}"><i class="fa fa-arrow-left"></i>back to list</a>
        </div>
        <table class="table">
            <tbody>
            <tr>
                <th>Id</th>
                <td>{{ trip.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ trip.title }}</td>
            </tr>
            <tr>
                <th>Keywords</th>
                <td>{{ trip.keywords }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ trip.description }}</td>
            </tr>
            {#            <tr>#}
            {#                <th>Type</th>#}
            {#                <td>{{ trip.type }}</td>#}
            {#            </tr>#}
            {#            <tr>#}
            {#                <th>Publisher_id</th>#}
            {#                <td>{{ trip.publisherId }}</td>#}
            {#            </tr>#}
            <tr>
                <th>Trip_start</th>
                <td>{{ trip.tripStart ? trip.tripStart|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Trip_end</th>
                <td>{{ trip.tripEnd ? trip.tripEnd|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>     <img src="{{ asset('uploads/image') }}/{{ trip.image.image }} " alt="" height="70px" width="60px" class="src">
                </td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ trip.price }}</td>
            </tr>
            </tbody>
        </table>



        <a class="btn-sm btn btn-success floatleft" href="{{ path('user_my_trip_edit', {'id': trip.id}) }}"><i class="fa fa-edit"></i>edit</a>

        {{ include('admin/admin/trip/_delete_form.html.twig') }}
    </div>
    {% include('home/User/user-lower.html.twig') %}
{% endblock %}

templates/home/User/user-my-trip.html.twig
{% extends('admin/homeBase.html.twig') %}

{% block body %}
    {% include('home/User/user-upper.html.twig') %}
    <table class="table table-striped table-responsive">
        <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Status</th>
            <th>Keywords</th>
            <th>Category</th>
            <th>Trip_start</th>
            <th>Trip_end</th>
            <th>Image</th>
            <th>Gallary</th>
            <th>Price</th>
            <th>Show</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for trip in trips %}
            <tr>
                <td>{{ trip.id }}</td>
                <td>{{ trip.title }}</td>
                <td>{{ trip.status }}</td>
                <td>{{ trip.keywords }}</td>
                <td>{{ trip.category.title }}</td>
                {#                            <td>{{ trip.type }}</td>#}
                {#                            <td>{{ trip.publisherId }}</td>#}
                <td>{{ trip.tripStart ? trip.tripStart|date('Y-m-d') : '' }}</td>
                <td>{{ trip.tripEnd ? trip.tripEnd|date('Y-m-d') : '' }}</td>
                <td>
                    {% if  trip.image == null %}
                        <a onclick="myFunction('{{ path('admin_trip_iedit',{'id': trip.id}) }}')" href="#">
                            <img src="{{ asset('assets/admin') }}/imag/image.jpg" alt="" height="30px" width="30px" class="src">
                        </a>
                    {% else %}
                        <a onclick="myFunction('{{ path('admin_trip_iedit',{'id': trip.id}) }}')" href="#">
                            <img src="{{ asset('uploads/image') }}/{{ trip.image.image }} " alt="" height="30px" width="30px" class="src">
                        </a>
                    {% endif %}
                    <script>
                        function myFunction(url) {
                            var myWindow = window.open(url, "", "width=500,height=500");
                        }
                    </script>
                </td>
                <td>
                    <a onclick="myFunction('{{ path('trip_image_gallery', {'id': trip.id}) }}')" href="#">
                        <img src="{{ asset('assets/images') }}/gallary.jpg" alt="" height="40px" width="30px" class="src">
                    </a>
                </td>
                <td>{{ trip.price }}</td>

                <td>
                    <a class="btn btn-sm btn-success" href="{{ path('user_my_trip_show', {'id': trip.id}) }}"> <i
                                class="fa fa-eye"> </i> show</a>
                </td>
                <td>
                    <a class="btn  btn-sm btn-info" href="{{ path('user_my_trip_edit', {'id': trip.id}) }}"> <i
                                class="fa fa-edit"></i> edit</a>
                </td>
                <td>
                    <form method="post" action="{{ path('user_trip_delete', {'id': trip.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ trip.id) }}">
                        <button class="btn btn-sm btn-danger floatright"><i class="fa fa-trash-o"></i>Delete</button>
                    </form>

                </td>
            </tr>

        {% else %}

            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
        <script>
            function onWarning() {
                window.alert("Trip Has Been Accepted. Can't delete trip.")
            }
        </script>
    </table>
    <div>
        <a class="btn btn-sm btn-primary" href="{{ path('user_my_trip_new') }}"> <i class="fa fa-newspaper-o " ></i>  Create new</a>
    </div>
    {% include('home/User/user-lower.html.twig') %}
{% endblock %}

templates/home/User/user-saved-list.html.twig
{% extends('admin/homeBase.html.twig') %}

{% block body %}
    {% include('home/User/user-upper.html.twig') %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Trip Title</th>
            <th>Trip's Price</th>
            <th>Trip's Start Date</th>
            <th>Added At</th>
            <th>View</th>
            <th>Delete</th>
            <th>Join</th>

        </tr>
        </thead>
        <tbody>
        {% for saved in saveds %}
            <tr>
                <th>{{ saved.trip.title }}</th>
                <th>{{ saved.trip.price }}</th>
                <th>{{ saved.trip.tripStart|date("m/d/Y") }}</th>
                <th>{{ saved.addedAt |date("m/d/Y") }}</th>
                <th><a href="{{ path('trip_detail', {'id' : saved.trip.id}) }}" class="btn btn-sm btn-info">View</a></th>
                <th>
                    <form method="post" action="{{ path('delete-saved-list', {'id': saved.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ saved.id) }}">
                        <button class="btn btn-sm btn-danger">Delete</button>
                    </form>
                </th>
                <th><a href="{{ path('add-to-joined-trip', {'id' : saved.trip.id}) }}" class="btn btn-sm btn-primary">Join</a></th>
{#                <th>{{ include('admin/admin/comment/_delete_form.html.twig') }}</th>#}
{#                <th><a href="{{ path('user-profile-comment-edit', {'id' : comment.id}) }}" class="btn btn-primary" style="text-transform:lowercase;">Edit</a></th>#}
            </tr>
        {% else %}
            <h5>No there is no saved trip in your list</h5>
        {% endfor %}
        </tbody>
    </table>
    {% include('home/User/user-lower.html.twig') %}
{% endblock %}