src/Entity/Category.php
<?php

namespace App\Entity;

use App\Entity\Admin\Image;
use App\Entity\Admin\userTrip;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CategoryRepository")
 */
class Category
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $parentid;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $keywords;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Admin\Image")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=34, nullable=true)
     */
    private $status;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getParentid(): ?Category
    {
        return $this->parentid;
    }

    public function setParentid(?Category $parentid): self
    {
        $this->parentid = $parentid;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }

    public function setKeywords(?string $keywords): self
    {
        $this->keywords = $keywords;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?Image
    {
        return $this->image;
    }

    public function setImage(?Image $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
    public function __toString()
    {
        // TODO: Implement __toString() method.
        return $this->getTitle();
    }

}

src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Entity\Admin\trip;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentRepository")
 */
class Comment
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $commented_by;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Admin\trip")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $on_trip;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $commented_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $subject;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $rating;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $ip;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getCommentedBy(): ?User
    {
        return $this->commented_by;
    }

    public function setCommentedBy(?User $commented_by): self
    {
        $this->commented_by = $commented_by;

        return $this;
    }

    public function getOnTrip(): ?trip
    {
        return $this->on_trip;
    }

    public function setOnTrip(?trip $on_trip): self
    {
        $this->on_trip = $on_trip;

        return $this;
    }

    public function getCommentedAt(): ?\DateTimeInterface
    {
        return $this->commented_at;
    }

    public function setCommentedAt(?\DateTimeInterface $commented_at): self
    {
        $this->commented_at = $commented_at;

        return $this;
    }

    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function setSubject(?string $subject): self
    {
        $this->subject = $subject;

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(?int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(?bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getIp(): ?string
    {
        return $this->ip;
    }

    public function setIp(?string $ip): self
    {
        $this->ip = $ip;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Admin\Image;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=44, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=22, nullable=true)
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Admin\Image")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $surname;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->name;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }
    public function __toString()
    {
        // TODO: Implement __toString() method.
        return $this->getEmail();
    }

    public function getImage(): ?Image
    {
        return $this->image;
    }

    public function setImage(?Image $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(?string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Admin\Message;
use App\Entity\Admin\trip;
use App\Entity\Comment;
use App\Form\Admin\MessageType;
use App\Form\CommentType;
use App\Repository\Admin\ImageRepository;
use App\Repository\Admin\tripRepository;
use App\Repository\CategoryRepository;
use App\Repository\CommentRepository;
use App\Repository\SettingRepository;
use App\Repository\SliderRepository;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\Bridge\Google\Smtp\GmailTransport;
use Symfony\Component\Mailer\Mailer;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     * @param SettingRepository $settingRepository
     * @param ImageRepository $imageRepository
     * @param SliderRepository $sliderRepository
     * @param tripRepository $tripRepository
     * @return Response
     */
    public function index(SettingRepository $settingRepository, ImageRepository $imageRepository, SliderRepository $sliderRepository, tripRepository $tripRepository)
    {

        /** @var TYPE_NAME $data */
        $setting = $settingRepository->findAll()[0];
//        $em = $this->getDoctrine()->getManager();
//        $silder = $statement->fetchAll();
//        dump($silder);
//        die();
        return $this->render('home/index.html.twig', [
            'title' => 'Trip | Travel Site',
            'keywords' => $setting->getKeywords(),
            'description' => $setting->getDescription(),
            'setting' => $setting,
            'trips' => $tripRepository->findBy(['status' => 'Published',], ['updated_at' => 'DESC']),
        ]);
    }

    /**
     * @Route("/aboutus", name="aboutus")
     * @param SettingRepository $settingRepository
     * @return Response
     */
    public  function aboutus( SettingRepository $settingRepository)
    {
        $setting = $settingRepository->findAll()[0];
        return $this->render('home/aboutus/aboutus.html.twig',[
            'title' => 'About Us | Travel Site',
            'keywords' => $setting->getKeywords(),
            'description' => $setting->getDescription(),
            'setting' => $setting,
    ]);

    }

    /**
     * @Route("/contantus", name="contantus", methods={"GET","POST"})
     * @param Request $request
     * @param SettingRepository $settingRepository
     * @param SliderRepository $sliderRepository
     * @param tripRepository $tripRepository
     * @return Response
     * @throws \Exception
     * @throws \Symfony\Component\Mailer\Exception\TransportExceptionInterface
     */
    public function contantus(Request $request, SettingRepository $settingRepository,SliderRepository $sliderRepository , tripRepository $tripRepository): Response
    {
        $setting = $settingRepository->findAll()[0];
        $data = $settingRepository->findAll();
        $message = new Message();
        $form = $this->createForm(MessageType::class, $message);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $message->setUpdatedAt(new DateTime());
            $message->setCreatedAt(new DateTime());
            $message->setIp($_SERVER['REMOTE_ADDR']);
            $message->setStatus("New");
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($message);
            $entityManager->flush();

            $email = (new Email())
                ->from($setting->getEmail())
                ->to($message->getEmail())
                //->cc('cc@example.com')
                //->bcc('bcc@example.com')
                //->replyTo('fabien@example.com')
                //->priority(Email::PRIORITY_HIGH)
                ->subject('You receive your message!')
                ->html('<p>Dear'. $message->getName() .',</p>'.
                        '<p>We successfully receive your message to us and thank you so much for sending to us</p>');

            /** @var Symfony\Component\Mailer\SentMessage $sentEmail */
            $transport = new GmailTransport($setting->getSmtpemail(), $setting->getSmtppassword());
            $mailer =  new Mailer($transport);
            $sentEmail = $mailer->send($email);
            // $messageId = $sentEmail->getMessageId();

            $this->addFlash('success', 'Messsage send');

            return $this->redirectToRoute('contantus');
        }

        return $this->render('home/contantus/contantus.html.twig', [
            'title' => 'Contact Us | Travel Site',
            'keywords' => $setting->getKeywords(),
            'description' => $setting->getDescription(),
            'message' => $message,
            'form' => $form->createView(),
            'data'=>$data,
            'setting' => $setting,
        ]);
    }


    /**
     * @Route("/trip/{id}", name="trip_detail", methods={"POST", "GET"})
     * @param Request $request
     * @param trip $trip
     * @param CategoryRepository $categoryRepository
     * @param CommentRepository $commentRepository
     * @return Response
     * @throws \Exception
     */
    public function tripDetail(Request $request, trip $trip, ImageRepository $imageRepository, CategoryRepository $categoryRepository, CommentRepository $commentRepository )
    {
        $category = $categoryRepository->findAll();
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        if($form->isSubmitted())
        {
            $comment->setOnTrip($trip);
            $comment->setIp($_SERVER['REMOTE_ADDR']);
            $comment->setCommentedAt(new DateTime());
            $comment->setUpdatedAt(new DateTime());
            $comment->setCommentedBy($this->getUser());
            $em = $this->getDoctrine()->getManager();
            $em->persist($comment);
            $em->flush();
        }
        return $this->render('home/TripDetail/TripDetail-index.html.twig',
            [
                'title' => $trip->getTitle(),
                'keywords' => $trip->getKeywords(),
                'description' => $trip->getDescription(),
                'trip' => $trip,
                'category' => $category,
                'comments' => $commentRepository->findBy(['on_trip' => $trip->getId()], ['commented_at' => 'ASC']),
                'images' => $imageRepository->findBy(['trip' => $trip]),

            ]);
    }






}

templates/home/TripDetail/TripDetail-index.html.twig
{% extends('admin/homeBase.html.twig') %}

{% block body %}

    <!-- single -->
    <div class="single">
        <div class="container">
            <div class="col-md-7 blog-left">
                <div class="blog-left-grid">
                    <h1>{{ trip.title }}</h1>
                    <ul>
                        <li><span class="glyphicon glyphicon-calendar"
                                  aria-hidden="true"></span>{{ trip.createdAt |date("m/d/Y") }}</li>
                        <li><a href="#"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>{{ comments|length }} Comment(s)</a>
                        </li>
                        <li><a href="#"><span class="glyphicon glyphicon-user"
                                              aria-hidden="true"></span>{{ trip.publisher.name }}</a></li>
                    </ul>

                    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">
                            {% for image in images %}
                                <div class="carousel-item {{ loop.index == 1 ? 'active' : "" }}">
                                    <img style="object-fit: cover; width: 100%; max-height: 450px;" src="{{ asset('uploads/image') }}/{{ image.image }}" alt="First slide">
                                </div>
                            {% endfor %}

                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                    <br><br>
                    {% for message in app.flashes('success-added-saved') %}
                        <div class="alert alert-success">
                            {{ message }} <a href="{{ path('user-saved-list') }}">Check</a>
                        </div>
                    {% endfor %}
                    {% for message in app.flashes('error-added-saved') %}
                        <div class="alert alert-danger">
                            {{ message }} <a href="{{ path('user-saved-list') }}">Check</a>
                        </div>
                    {% endfor %}
                    {% for message in app.flashes('success-added-joined') %}
                        <div class="alert alert-success">
                            {{ message }} <a href="{{ path('user-joined-list') }}">Check</a>
                        </div>
                    {% endfor %}
                    {% for message in app.flashes('error-added-joined') %}
                        <div class="alert alert-danger">
                            {{ message }} <a href="{{ path('user-joined-list') }}">Check</a>
                        </div>
                    {% endfor %}
                    {% if app.user %}
                    {% if app.user == trip.publisher %}
                        <h6>This trip was created by you. You can't join to the trip that was created by you.</h6>
                    {% else %}
                    <a href="{{ path('add-to-saved-trip', {'id': trip.id}) }}" class="btn btn-info">Add To Saved</a>
                    <a href="{{ path('add-to-joined-trip', {'id': trip.id}) }}" class="btn btn-primary">Join The Trip</a>
                    {% endif %}

                    {% else %}
                        <h6>Please Login To Save and Join this Trip <a href="{{ path('app_login') }}">Login</a></h6>
                    {% endif %}

                    <div class="">
                        {{ trip.content | raw }}
                    </div>
                </div>
                <div class="com">
                    <h3>Comments</h3>
                    <ul class="media-list">
                        {% for comment in comments %}
                            {% if comment.status %}
                            <li class="media">
                                <div class="media-left">
                                    <a href="#">
                                        <img class="media-object" src="{{ asset('uploads/image/') }}{{ comment.commentedBy.image }}" alt=""/>
                                    </a>
                                </div>
                                <div class="media-body">
                                    <h4 class="media-heading">{{ comment.commentedBy.username }} </h4>
                                    {% for i in 1..comment.rating%}
                                        <i class="fa fa-star-o"></i>
                                    {% endfor %}
                                    <h5>{{ comment.subject }}  </h5>
                                    {{ comment.comment }}
                                </div>
                            </li>
                            {% endif %}
                        {% else %}
                            <h3>There is no comment yet</h3>
                        {% endfor %}

                    </ul>
                </div>
            </div>
            <div class="col-md-5 blog-right " style="padding-top: 120px">
                <div class="blog-right1">
                    <div class="categories">
                        <h3>Category</h3>
                        <ul>
                            <li><a href="#">{{ trip.category.title }}</a></li>
                        </ul>
                        <ul>
                            <li>
                                <p>Description</p>
                                <p>{{ trip.description }}</p>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                <p>Price</p>
                                    <p>{{ trip.price }}</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="leave-a-comment">
                <h3>Leave your comment Here</h3>
                {% if app.user %}
                <form action="" name="comment" method="post">
                    <input type="number" name="comment[commented_by]" hidden value="{{ app.user.id }}">
                    <input type="number" name="comment[on_trip]" hidden value="{{ trip.id }}">
                    <input type="number" name="comment[status]" hidden value="1">
                    <div>
                        <label>Subject</label> <br>
                        <input type="text" name="comment[subject]" value="" class="form-control">
                    </div>
                    <div>
                        <label>Rating</label> <br>
                        <select name="comment[rating]" id="" class="form-control">
                            <option value="1" selected>1</option>
                            <option value="2" >2</option>
                            <option value="3" >3</option>
                            <option value="4" >4</option>
                            <option value="5" >5</option>
                        </select>
                    </div>
                    <div>
                        <label>Comment</label> <br>
                        <textarea name="comment[comment]" type="text" rows="3" aria-placeholder="Type Your Comment here..."></textarea>
                    </div>
                    <input type="submit" value="Add Comment">
                </form>
                {% else %}
                    <h6>Please Login To Comment <a href="{{ path('app_login') }}">Login</a></h6>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- //single -->
    <script>
        function onWarning() {
            window.alert("You can't do anything be for login!!!!!.")
        }
    </script>
{% endblock %}